### ISSUE TITLE
Wallpaper configuration does not show

### ISSUE THREAD

**Issue by Findarato** [hhannine/superpaper#114] opened 2022-03-08 14:13 UTC
**Describe the bug**
When I start superpaper with a configured setup it works, but will not show wallpaper configuration

**To Reproduce**
1. Start the app
2. Right click on icon in tray
3. Click on **Wallpaper Configuration**

**Expected behavior**
Wallpaper configuration screen should snow

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Desktop Environment on Linux: Gnome 41
 - Superpaper package & version: PIP 2.1.0 with pyton 3.10

```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: superpaper in ./.local/lib/python3.10/site-packages (2.1.0)
Requirement already satisfied: Pillow>=7.0.0 in /usr/lib64/python3.10/site-packages (from superpaper) (8.3.2)
Requirement already satisfied: xcffib>=0.8.0 in ./.local/lib/python3.10/site-packages (from superpaper) (0.11.1)
Requirement already satisfied: screeninfo>=0.6.1 in ./.local/lib/python3.10/site-packages (from superpaper) (0.8)
Requirement already satisfied: numpy>=1.18.0 in ./.local/lib/python3.10/site-packages (from superpaper) (1.21.4)
Requirement already satisfied: system-hotkey>=1.0.3 in ./.local/lib/python3.10/site-packages (from superpaper) (1.0.3)
Requirement already satisfied: xpybutil>=0.0.5 in ./.local/lib/python3.10/site-packages (from superpaper) (0.0.6)
Requirement already satisfied: six in /usr/lib/python3.10/site-packages (from xcffib>=0.8.0->superpaper) (1.16.0)
Requirement already satisfied: cffi>=1.1.0 in ./.local/lib/python3.10/site-packages (from xcffib>=0.8.0->superpaper) (1.15.0)
Requirement already satisfied: pycparser in ./.local/lib/python3.10/site-packages (from cffi>=1.1.0->xcffib>=0.8.0->superpaper) (2.21)
```

**Additional context**

Logging / debugging contents:
```
Traceback (most recent call last):
  File "/home/joe/.local/lib/python3.10/site-packages/superpaper/tray.py", line 60, in <lambda>
    menu.Bind(wx.EVT_MENU, lambda event: func(event, *args), id=item.GetId())
  File "/home/joe/.local/lib/python3.10/site-packages/superpaper/tray.py", line 299, in configure_wallpapers
    config_frame = ConfigFrame(self)
  File "/home/joe/.local/lib/python3.10/site-packages/superpaper/gui.py", line 31, in __init__
    config_panel = WallpaperSettingsPanel(self, parent_tray_obj)
  File "/home/joe/.local/lib/python3.10/site-packages/superpaper/gui.py", line 74, in __init__
    self.wpprev_pnl = WallpaperPreviewPanel(self, self.display_sys)
  File "/home/joe/.local/lib/python3.10/site-packages/superpaper/gui.py", line 1363, in __init__
    self.draw_displays()
  File "/home/joe/.local/lib/python3.10/site-packages/superpaper/gui.py", line 1381, in draw_displays
    bmp_canv = wx.Bitmap.FromRGBA(self.dtop_canvas_relsz[0], self.dtop_canvas_relsz[1], red=0, green=0, blue=0, alpha=255)
TypeError: Bitmap.FromRGBA(): argument 1 has unexpected type 'float'
```

**Comment by hhannine** [comment] 2022-03-08 19:14
Thanks for the report. The issue was caused by incompatibility with Python 3.10 and it is fixed in the master branch. You can either clone the repo and install the repo version with `pip3 install --user .` by running in the cloned superpaper directory. Alternatively you can use older Python, probably.

**Closed by hhannine** 2022-03-08 19:14 UTC
