### ISSUE TITLE
3 Monitor setup with one portrait (span mode not set automatically)

### ISSUE THREAD

**Issue by andia89** [hhannine/superpaper#44] opened 2020-05-06 07:51 UTC
I have a setup with two landscape monitors and one portrait monitor running Ubuntu 20.04. 
Superpaper seems to detect that properly (everything is default values, no additional perspective settings etc.) and the preview looks fine.

![image](https://user-images.githubusercontent.com/6475757/81149538-ada2cb80-8f7e-11ea-8c64-70fb354addb8.png)

However when pressing apply it looks like that.

![Screenshot from 2020-05-06 09-49-09](https://user-images.githubusercontent.com/6475757/81149678-f6f31b00-8f7e-11ea-8ea0-13be12d10f8f.png)

So it is quite messed up. It seems that everything is detected properly but then not applied to the settings it is detected.

**Comment by hhannine** [comment] 2020-05-06 07:55
As it is now, it is necessary to set the wallpaper span mode to 'spanned' from Gnome Tweaks. Or alternatively from the terminal
```
gsettings set org.gnome.desktop.background picture-options 'spanned'
```
I've got a todo to implement this to be applied automatically.

**Comment by hhannine** [comment] 2020-05-08 06:15
Duplicate of #40

**Closed by hhannine** 2020-05-08 06:15 UTC
