### ISSUE TITLE
Locale 'en_US' cannot be set. Manjaro KDE

### ISSUE THREAD

**Issue by baimahambetov** [hhannine/superpaper#121] opened 2022-06-19 09:07 UTC
![image](https://user-images.githubusercontent.com/58873710/174473724-79767eee-49a6-46c8-afd8-f30d0d2f6c8c.png)

**Comment by Roy-Orbison** [comment] 2022-08-11 02:55
Same for `en_AU` on Kubuntu.

**Comment by hhannine** [comment] 2022-11-05 20:58
Which installation type are you using? Is this problem still persisting?

**Comment by Roy-Orbison** [comment] 2022-11-07 02:15
I just tried again, using `pip install --user superpaper` like last time, same issue. `pip --version` reports 3.10.

**Comment by hhannine** [comment] 2022-11-07 10:34
Okay thanks for checking. I found something relevant for the problem in wxpython, posting this discussion for my own refrence: https://stackoverflow.com/a/70659777

**Comment by hhannine** [comment] 2022-11-08 07:14
This is hopefully now resolved by 746ab8093e9af7d88f71a422b06b6e7626e749de. Could you try to run the version from Github to test it?

**Comment by Roy-Orbison** [comment] 2022-11-09 01:08
I ran
```sh
pip install 'git+https://github.com/hhannine/superpaper.git#egg=superpaper'
```
It works, except for configuring bezels. I have nothing to compare it to, so I'm unsure of whether the issue is triggered by this fix or if it's unrelated. I click on the centre bezel button to adjust the gap between monitors, but I cannot enter a number. I tried both the top row and numpad keys, as well as `+` and `-`. I can work around it by right-clicking on the input to get a context menu, then using _Select all_ & _Paste_ with a copied number. Qt version is 5.15.6 if that helps.

**Comment by hhannine** [comment] 2022-11-09 06:40
Very good! Thanks!

Okay, I've been having similar problems with the bezel entry box on Windows as well, it has been annoyingly platform specific problem. What is your wxPython version?

**Comment by Roy-Orbison** [comment] 2022-11-09 07:56
4.0.7

**Comment by Roy-Orbison** [comment] 2022-11-09 23:49
I tried, but got this error:
```text
ModuleNotFoundError: No module named 'attrdict'
```
After I resolved that, I got this:
```text
ImportError: cannot import name 'Mapping' from 'collections'
```
which I don't know how to resolve.

**Comment by hhannine** [comment] 2022-11-10 06:48
Thanks. Seems to be some problem with building wxPython, unfortunate.

However, they have 'wheels' for Ubuntu, so they should work if you're running Kubuntu(?). See here how to install from a wheel: https://wxpython.org/pages/downloads/

**Closed** 2022-11-22 21:53 UTC
