### ISSUE TITLE
SuperPaper won't start: OnInit returned false, exiting...

### ISSUE THREAD

**Issue by dct-LuLu** [hhannine/superpaper#108] opened 2022-01-19 17:41 UTC
Hi, I'm running I3wm, dual screen, EndeavourOS, and Python 3.10.1. When I run SuperPaper in debug mode I get the following:

```
/usr/lib/python3.10/site-packages
/home/atlanteavour-morphium/.config/superpaper
/home/atlanteavour-morphium/.config/superpaper/profiles
None
None
None
None
None
None
True
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1920, 1080), (1920, 1080)], OFF_ARR = [(0, 0), (1920, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(160, 90), detected_phys_size_mm=(160, 90), ppi=304.79999999999995, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-1')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(854, 480), detected_phys_size_mm=(854, 480), ppi=57.10538641686182, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-0')
load_system: archive_file not found: /home/atlanteavour-morphium/.config/superpaper/display_systems.dat
START Listing profiles for menu.
hkBinding: ('control', 'super', 'shift', 'h')
Listed profile: example
hkBinding: ('control', 'super', 'shift', 'g')
Listed profile: example_multi
END Listing profiles for menu.
No previous profile was found.
hkBinding: ('control', 'super', 'shift', 'h')
Listed profile: example
hkBinding: ('control', 'super', 'shift', 'g')
Listed profile: example_multi
Registering binding:                                 ('control', 'super', 'shift', 'h') for profile: example
Registering binding:                                 ('control', 'super', 'shift', 'g') for profile: example_multi
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1920, 1080), (1920, 1080)], OFF_ARR = [(0, 0), (1920, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(160, 90), detected_phys_size_mm=(160, 90), ppi=304.79999999999995, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-1')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(854, 480), detected_phys_size_mm=(854, 480), ppi=57.10538641686182, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-0')
load_system: archive_file not found: /home/atlanteavour-morphium/.config/superpaper/display_systems.dat
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/superpaper/tray.py", line 472, in OnInit
    TaskBarIcon(frame)
  File "/usr/lib/python3.10/site-packages/superpaper/tray.py", line 115, in __init__
    config_frame = ConfigFrame(self)
  File "/usr/lib/python3.10/site-packages/superpaper/gui.py", line 31, in __init__
    config_panel = WallpaperSettingsPanel(self, parent_tray_obj)
  File "/usr/lib/python3.10/site-packages/superpaper/gui.py", line 74, in __init__
    self.wpprev_pnl = WallpaperPreviewPanel(self, self.display_sys)
  File "/usr/lib/python3.10/site-packages/superpaper/gui.py", line 1363, in __init__
    self.draw_displays()
  File "/usr/lib/python3.10/site-packages/superpaper/gui.py", line 1381, in draw_displays
    bmp_canv = wx.Bitmap.FromRGBA(self.dtop_canvas_relsz[0], self.dtop_canvas_relsz[1], red=0, green=0, blue=0, alpha=255)
TypeError: Bitmap.FromRGBA(): argument 1 has unexpected type 'float'
OnInit returned false, exiting...
```
I have feh installed, and I don't think there's any wallpaper manager that could be conflicting

**Comment by hhannine** [comment] 2022-02-08 19:55
Duplicate of #103

**Closed by hhannine** 2022-02-08 19:55 UTC
