### ISSUE TITLE
Errors on open.

### ISSUE THREAD

**Issue by Aidiah** [hhannine/superpaper#55] opened 2020-06-04 02:56 UTC
**Describe the bug**
Errors on trying to open.

**Desktop:**
 - OS: Manjaro
 - Desktop Environment on Linux: KDE/Plasma 5.18.5
 - Superpaper package & version: aur/superpaper 2.0.2-1

Logging / debugging contents:
```
$ superpaper -d
/usr/lib/python3.8/site-packages
/home/dan/.config/superpaper
/home/dan/.config/superpaper/profiles
Traceback (most recent call last):
  File "/usr/bin/superpaper", line 11, in <module>
    load_entry_point('superpaper==2.0.2', 'console_scripts', 'superpaper')()
  File "/home/dan/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dan/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/home/dan/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/home/dan/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/superpaper/__main__.py", line 13, in <module>
    from superpaper.cli import cli_logic
  File "/usr/lib/python3.8/site-packages/superpaper/cli.py", line 8, in <module>
    from superpaper.data import CLIProfileData
  File "/usr/lib/python3.8/site-packages/superpaper/data.py", line 15, in <module>
    import superpaper.wallpaper_processing as wpproc
  File "/usr/lib/python3.8/site-packages/superpaper/wallpaper_processing.py", line 19, in <module>
    from PIL import Image, UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (/usr/lib/python3.8/site-packages/PIL/__init__.py)
```

**Comment by hhannine** [comment] 2020-06-04 07:23
Duplicate of #53. The AUR package is not made my me so I can't fix the issue. It has been reported there.

**Closed** 2020-06-04 10:33 UTC
