### ISSUE TITLE
Superpaper began failing to start after system updates

### ISSUE THREAD

**Issue by TheAmazingDave** [hhannine/superpaper#122] opened 2022-06-23 01:28 UTC
openSUSE Tumbleweed running KDE Plasma X11, Superpaper installed via Zypper.

After accepting a slew of updates a few days ago, Superpaper would no longer launch. Selecting the icon from launcher menu would kick it off, with the icon briefly appearing in the taskbar, but would then quit with no information, and no orphaned running processes.

Attempting to start Superpaper from cli however revealed the problem. This is the output:
`dave@Dave-XPS8920:~> superpaper
/usr/lib/python3.10/site-packages
/home/dave/.config/superpaper
/home/dave/.config/superpaper/profiles
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/superpaper/tray.py", line 472, in OnInit
    TaskBarIcon(frame)
  File "/usr/lib/python3.10/site-packages/superpaper/tray.py", line 109, in __init__
    self.register_hotkeys()
  File "/usr/lib/python3.10/site-packages/superpaper/tray.py", line 169, in register_hotkeys
    self.hk.register(
  File "/usr/lib/python3.10/site-packages/system_hotkey/util.py", line 118, in decorator
    self.bug_catcher.catch_and_raise(function, timeout)
  File "/usr/lib/python3.10/site-packages/system_hotkey/util.py", line 40, in catch_and_raise
    self._check_for_errors(func)
  File "/usr/lib/python3.10/site-packages/system_hotkey/util.py", line 75, in _check_for_errors
    raise error
  File "/usr/lib/python3.10/site-packages/system_hotkey/util.py", line 50, in decorator
    results = function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/system_hotkey/system_hotkey.py", line 284, in register
    assert isinstance(hotkey, collections.Iterable) and type(hotkey) not in (str, bytes)
AttributeError: module 'collections' has no attribute 'Iterable'
OnInit returned false, exiting...`

After a few quick searches, it appears that `collections.Iterable` is now deprecated and is no longer supported in current Python versions since 3.8. I guess Python was updated on my system which must have been using an older version previously.

It has been replaced by `collections.abc.Iterable`

I modified the file system_hotkey.py and changed the line to the new value.

Superpaper now launches properly again.

<3

**Comment by labatts** [comment] 2022-08-28 12:28
I had the same problem.  I was able to do your suggestion, and it starts minimized to the tray.  However, I am unable to access the configuration window.  I can right click the tray icon and have it go the the next wallpaper and such, but this is only from my previous config.  I have tried blowing up the local config folder, and that does not help.  Any suggestions?

**Comment by labatts** [comment] 2022-08-28 18:59
Okay, I see from here: https://bytemeta.vip/repo/hhannine/superpaper/issues/103 that the maintainer is aware of the issue and apparently has a fix in the upcoming release.

**Comment by hhannine** [comment] 2022-08-28 19:19
Thanks and sorry for the lack of updates. The main branch here at GitHub should be working so you can clone it and install it, and it should be fine. (I think the command should be `pip install . --upgrade` when ran in the root folder of the repo.

The RGBA issue is fixed in main, system_hotkey needs the user fix. I'll close this since the remaining issue is duplicate of #102.

**Closed by hhannine** 2022-08-28 19:19 UTC
