### ISSUE TITLE
Unable to Install SuperPaper

### ISSUE THREAD

**Issue by jdferron** [hhannine/superpaper#19] opened 2019-12-23 13:21 UTC
I am unable to install SuperPaper.  I am running Linux Mint 19.3   The steps I performed are as follows:

1. Installed python3-wxgtk4.0 via apt-get
2. Installed python3-pip due to it not being installed
3. Ran the following command: pip3 install -U superpaper.  Below is the output from that command
Collecting superpaper
Downloading https://files.pythonhosted.org/packages/3e/18/072c913b771b7c7651474ff324852ec87d4aa00581115deb12aaaf496210/superpaper-1.2.0-py3-none-any.whl (239kB)
100% |████████████████████████████████| 245kB 2.3MB/s
Collecting Pillow>=6.0.0 (from superpaper)
Downloading https://files.pythonhosted.org/packages/10/5c/0e94e689de2476c4c5e644a3bd223a1c1b9e2bdb7c510191750be74fa786/Pillow-6.2.1-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
100% |████████████████████████████████| 2.1MB 451kB/s
Collecting screeninfo>=0.6.1 (from superpaper)
Downloading https://files.pythonhosted.org/packages/fd/4f/3de7c674bb8a819ce2cfc125b6676039e9dfcb79398d8638f4b79650129d/screeninfo-0.6.1.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z6vyfpkf/screeninfo/

**Comment by hhannine** [comment] 2019-12-24 13:30
I did some digging and found a quote from a pipenv contributor:
> setuptools is a special package that should be provided by the base python installation (much like pip) and will always be excluded.

So this might be something that's out of my hands.

**Comment by jdferron** [comment] 2019-12-24 18:42
After installing setuptools, a new error:
Collecting superpaper
  Using cached https://files.pythonhosted.org/packages/3e/18/072c913b771b7c7651474ff324852ec87d4aa00581115deb12aaaf496210/superpaper-1.2.0-py3-none-any.whl
Collecting system-hotkey>=1.0.3 (from superpaper)
  Downloading https://files.pythonhosted.org/packages/65/b6/45b821fad7be5d43f99ed1e0c69e7e9116fd69c450ba164aad42c714fe68/system_hotkey-1.0.3-py3-none-any.whl
Collecting Pillow>=6.0.0 (from superpaper)
  Using cached https://files.pythonhosted.org/packages/10/5c/0e94e689de2476c4c5e644a3bd223a1c1b9e2bdb7c510191750be74fa786/Pillow-6.2.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting screeninfo>=0.6.1 (from superpaper)
  Using cached https://files.pythonhosted.org/packages/fd/4f/3de7c674bb8a819ce2cfc125b6676039e9dfcb79398d8638f4b79650129d/screeninfo-0.6.1.tar.gz
Collecting xcffib>=0.8.0 (from superpaper)
  Downloading https://files.pythonhosted.org/packages/16/d2/8658ed194e8b482af8d9ad2c5ddd126f1fb3553659f45be495ded371f3b6/xcffib-0.8.1.tar.gz (82kB)
    100% |████████████████████████████████| 92kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/jeff/.local/lib/python3.6/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_p1b_06k', '--quiet', 'pycparser']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8n2jjhks/xcffib/setup.py", line 96, in <module>
        **cffi_args
      File "/home/jeff/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/jeff/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/jeff/.local/lib/python3.6/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/jeff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/jeff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/jeff/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/jeff/.local/lib/python3.6/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/jeff/.local/lib/python3.6/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_p1b_06k', '--quiet', 'pycparser']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8n2jjhks/xcffib/

**Comment by jdferron** [comment] 2019-12-26 21:41
Gave up and uninstalled everything.

**Comment by hhannine** [comment] 2019-12-27 11:46
Sorry to hear that. I haven't had time to look into this, but based on the log you posted I would've tried installing the package 'wheel'. This perplexes me as to why you would need it to install the packages since I seem to have a fairly clear memory of installing wheel the first time when preparing the PyPI release, having installed the dependencies manually multiple times prior.

**Comment by hhannine** [comment] 2019-12-30 13:29
I'll close this for now since I can't reproduce the issue. Come and write back if you try again and have issues.

**Closed by hhannine** 2019-12-30 13:29 UTC

**Comment by lancelinksp** [comment] 2020-05-12 15:43
Just for an update on this, I ran in to the same problems and as suggested to install the python3-wheel package the install completed successfully and after reboot I was able to then see the application installed
