### ISSUE TITLE
Infinite spinning cursor in Windows v2.2.1, no changes saved or applied, but no crash either

### ISSUE THREAD

**Issue by nonplayer** [hhannine/superpaper#136] opened 2023-01-18 15:34 UTC
**Describe the bug**
Using version 2.2.1 on Windows 10 Pro 22H2, either portable or installed, any attempt to save profile or apply changes results in infinite spinning cursor with no visible action. Profiles do not get saved, wallpapers do not get applied.

However, there is no crash or "not responding" message. The app continues to run, the tray icon remains, and the Settings menu can be updated and changed as normal. Only the Wallpaper Config menu seems affected.

I tried this on a machine previously running 2.1.1, as well as a brand new machine without a prior Superpaper version. On both machines, 2.2.1 resulted in this issue. On both machines, either reverting to or subsequently installing anew with 2.1.1 resulted in normal expected operations.

**To Reproduce**

1. Install 2.2.1. on Windows
2. Attempt to create a new profile
3. Attempt to either Save profile or Apply changes

Results: infinite cursor spin, no change, but no crash.

**Expected behavior**

Saving a profile and applying changes should have the normal expected results of said actions.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit 22H2 build 19045.2486
 - Superpaper package & version: Windows v2.2.1, either Installer or Portable version

**Comment by hhannine** [comment] 2023-01-20 06:54
I was able to reproduce this:
`Traceback (most recent call last):
  File "\superpaper\gui.py", line 1145, in onSave
    self.parent_tray_obj.update_hotkey(tmp_profile.name, old_profile.hk_binding, tmp_profile.hk_binding)
AttributeError: 'NoneType' object has no attribute 'hk_binding'`
This is a bug in a recent change.

Luckily the issue is with the binding of the hotkey of the newly saved profile, and the profile is actually saved. If you shutdown superpaper and run it again, you should be able to start the newly saved profile.

**Comment by hhannine** [comment] 2023-01-20 06:55
Also you can run the previous 2.1 version and should not have any issues on Windows.

**Comment by hhannine** [comment] 2023-01-20 08:41
This is now resolved and fix will be in next release. Meanwhile you can run Superpaper 2.1

**Closed by hhannine** 2023-01-20 08:41 UTC
