### ISSUE TITLE
Does not set wallpaper on Gnome 42 when using dark theme

### ISSUE THREAD

**Issue by TimeLincoln** [hhannine/superpaper#125] opened 2022-08-02 14:26 UTC
When using the Dark theme in gnome 42, superpaper does not set the wallpapers, only works when gnome is set ot the light theme.

**Comment by TimeLincoln** [comment] 2022-08-02 14:45
Worked around this by setting picture-uri-dark to the same value as picture-uri in /org/gnome/desktop/background using dconf editor

**Comment by TimeLincoln** [comment] 2022-08-02 15:44
Set a custom command to update picture-uri-dark but seems like the custom command is only run once, not run each time the wallpaper switches so half the time i have the background color and half the time i have a wallpaper right now.

**Comment by TimeLincoln** [comment] 2022-08-02 17:19
added the set_command to the multi_profile and that fixed it.

**Comment by Commenter25** [comment] 2022-08-10 18:39
Duplicate of #119, fixed by #123

**Closed** 2022-11-04 22:20 UTC
