### ISSUE TITLE
The binary is not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by cwhy** [hhannine/Superpaper#7] opened 2019-06-14 07:46 UTC
Tested the binary in Ubuntu 16.04 by `./superpaper` and only found the following error message:
```
ERROR: Module 'wx' import has failed. Is it installed? GUI unavailable, exiting.
ERROR: Module 'wx' import has failed. Is it installed? GUI unavailable, exiting.
Traceback (most recent call last):
  File "superpaper.pyw", line 2642, in <module>
  File "superpaper.pyw", line 2636, in main
  File "superpaper.pyw", line 2628, in tray_loop
NameError: name 'exit' is not defined
[20733] Failed to execute script superpaper
```

**Comment by hhannine** [comment] 2019-06-14 19:04
Are you running the v1.1.2 release? Try running it with the debugging switch, does it print any additional messages?

**Comment by hhannine** [comment] 2019-07-11 12:16
Given that there hasn't been a response to this in a month and I can't reproduce this, I'll be closing this. Report back if issue persists.

**Closed by hhannine** 2019-07-11 12:16 UTC
